name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker qiskit
      run: docker build --build-arg quantum_env=qiskit.sh . --file Dockerfile --tag quantum_lab_qiskit:main
    - name: Build the Docker qml
      run: docker build --build-arg quantum_env=qml.sh . --file Dockerfile --tag quantum_lab_qml:main
    - name: Build the Docker q#
      run: docker build --build-arg quantum_env=qml.sh . --file Dockerfile --tag quantum_lab_qml:main
