name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_qiskit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker qiskit
      run: docker build . --file Dockerfile --tag quantum_lab_qiskit:main
