name: Docker TAG CI

on:
  workflow_dispatch:
  push:
    tags:        
      - '*'
jobs:

  build_qiskit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build qiskit and push to Docker Hub
      env:
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker build . --file Dockerfile --tag mickahell/quantum_lab_qiskit:${RELEASE_VERSION}
        docker tag mickahell/quantum_lab_qiskit:${RELEASE_VERSION} mickahell/quantum_lab_qiskit:latest
        docker login --username=mickahell --password=${DOCKERHUB_PASS}
        docker push mickahell/quantum_lab_qiskit --all-tags
