name: Docker Image CI

on: tags

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      -
        uses: actions/checkout@v2
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag quantum_lab_${quantum_env}:$(date +%s)
        with:
          quantum_env: ${{ quantum_env }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
