name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_qiskit:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker qiskit
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      run: |
        echo "toto : ${DOCKERHUB_USER}"
        echo ${DOCKERHUB_USER}
        docker build --build-arg quantum_env=qiskit.sh . --file Dockerfile --tag quantum_lab_qiskit:main

  build_qml:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker qml
      run: docker build --build-arg quantum_env=qml.sh . --file Dockerfile --tag quantum_lab_qml:main

  build_qsharp:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Q#
      run: docker build --build-arg quantum_env=qsharp.sh . --file Dockerfile --tag quantum_lab_qsharp:main

