name: Docker TAG CI

on:
  push:
    tags:        
      - '*'
jobs:

  build_qiskit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build qiskit and push to Docker Hub
      env:
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker build --build-arg quantum_env=qiskit.sh . --file Dockerfile --tag mickahell/quantum_lab_qiskit:$(date +%s)
        docker login --username=mickahell --password=${DOCKERHUB_PASS}
        docker push mickahell/quantum_lab_qiskit

  build_qml:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker qml
      env:
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker build --build-arg quantum_env=qml.sh . --file Dockerfile --tag mickahell/quantum_lab_qml:$(date +%s)
        docker login --username=mickahell --password=${DOCKERHUB_PASS}
        docker push mickahell/quantum_lab_qml

  build_qsharp:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Q#
      env:
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker build --build-arg quantum_env=qsharp.sh . --file Dockerfile --tag mickahell/quantum_lab_qsharp:$(date +%s)
        docker login --username=mickahell --password=${DOCKERHUB_PASS}
        docker push mickahell/quantum_lab_qsharp
