name: Docker TAG CI

on:
  push:
    tags:        
      - '*'
jobs:

  build_qiskit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build qiskit and push to Docker Hub
      run: |
        docker build --build-arg quantum_env=qiskit.sh . --file Dockerfile --tag ${DOCKERHUB_USERNAME}/quantum_lab_qiskit:$(date +%s)
        docker login --username=${DOCKERHUB_USERNAME} --email=${DOCKERHUB_EMAIL} --password=${DOCKERHUB_PASSWORD}
        docker push ${DOCKERHUB_USERNAME}/quantum_lab_qiskit

  build_qml:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker qml
      run: |
        docker build --build-arg quantum_env=qml.sh . --file Dockerfile --tag ${DOCKERHUB_USERNAME}/quantum_lab_qml:$(date +%s)
        docker login --username=${DOCKERHUB_USERNAME} --email=${DOCKERHUB_EMAIL} --password=${DOCKERHUB_PASSWORD}
        docker push ${DOCKERHUB_USERNAME}/quantum_lab_qml

  build_qsharp:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Q#
      run: |
        docker build --build-arg quantum_env=qsharp.sh . --file Dockerfile --tag ${DOCKERHUB_USERNAME}/quantum_lab_qsharp:$(date +%s)
        docker login --username=${DOCKERHUB_USERNAME} --email=${DOCKERHUB_EMAIL} --password=${DOCKERHUB_PASSWORD}
        docker push ${DOCKERHUB_USERNAME}/quantum_lab_qsharp
